config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "reviews#index"
  resources :wines, only: [:show] do
    collection do
      get 'search'
      get 'autocomplete'
    end
    resources :reviews, only: [:new, :create, :edit, :update, :show]
  end
  resources :reviews, only: [:index, :destroy]
  resources :users, only: [:edit, :update, :show]
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer>Copyright©️2024 IamSommelier</footer>

app/views/shared/_header.html.erb
<header>
      
      <div class="navbar">

        <div class="nav-left">
          <div><%= link_to(image_tag("wine_nomitai.png", alt: "ロゴ", class: "header-image"), root_path) %></div>
          <div class="nav"><a href="#">ワ活</a></div>
          <div class="nav"><a href="#">ニュース</a></div>
        </div>
        
        <div class="nav-right">
          <% if user_signed_in? %>
          <div><%= link_to 'ログアウト', destroy_user_session_path, data: {turbo_method: :delete}, class: "log-out" %></div>
          <div class="header-image"><%= link_to(image_tag("bell.png", alt: "通知", class: "header-image"), "#") %></div>
          
          <% else %>
          <div><%= link_to '新規登録', new_user_registration_path, class: "sign-in" %></div>
          <div><%= link_to 'ログイン', new_user_session_path, class: "log-in" %></div>
          <%  end %>
          
          
          <% if current_user %>
            <div class="icon">
              <%= link_to(
                image_tag(current_user.avatar.attached? ? current_user.avatar : 'wa.png', class: "icon"),
                user_path(current_user)
              ) %>
            </div>
          <% end %>
        </div>

      </div>

</header>

app/views/shared/_review_index.html.erb
<div class="main-second">
  <div class="reviews">
    <% if @reviews.any? %>
      <% @reviews.each do |review| %>
        <div class="review">     
          <div class="review-top">
            <%= link_to(image_tag(review.user.avatar, alt: review.user.nickname, class: "avatar"), user_path(review.user)) %>
            
            <div class="date-name">
            <div class="wine-date"><%= review.wine_date %></div>
            <div class="user-name"><%= link_to review.user.nickname, user_path(review.user), class: "user-name-color" %></div>
            </div>
            
            <div class="wine-name">
              <%= link_to "#{review.wine.name} （ #{Region.find(review.wine.region_id).name} ）", wine_path(review.wine), class: "wine-name-color" %>
            </div>
            
          </div>

          <div class="review-content">
            <div class="review-image">
              <% if review.image.attached? %>
                <%= link_to image_tag(review.image, class: "review-image"), "#" %>
              <% end %>
            </div>
            <div class="review-text"><%= review.content %>

            <ul class="link-to-show">
               <li><%= link_to "詳細", wine_review_path(wine_id: review.wine_id, id: review.id), class: "show-link" %></li>
            </ul>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <div class="no-reviews">
        <p>まだレビューがありません。あなたのレビューを投稿してください！</p>
      </div>
    <% end %>
  </div>
</div>