config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "reviews#index"
  resources :wines, only: [:show] do
    collection do
      get 'search'
      get 'autocomplete'
    end
    resources :reviews, only: [:new, :create, :edit, :update, :show]
  end
  resources :reviews, only: [:index, :destroy]
  resources :users, only: [:edit, :update, :show]
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_wine, only: [:new, :create, :edit, :update, :show]

  def index
    @reviews = Review.order(created_at: :desc).limit(5)
  end

  def new
    @review = @wine.reviews.build
  end

  def create
    @wine = Wine.find(params[:wine_id])
    @review = @wine.reviews.build(review_params.except(:fragrances))
    @review.user = current_user

    # 安全にfragrance_idsを取得し、Fragranceオブジェクトを設定
    fragrance_ids = Array.wrap(params[:review].dig(:fragrances, :fragrance_ids)).map(&:to_i)
    @review.fragrances = Fragrance.where(id: fragrance_ids)

    if @review.save
      redirect_to @wine
    else
      render :new
    end
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])

    if @review.update(review_params.except(:fragrances))
      # 安全にfragrance_idsを取得し、Fragranceオブジェクトを設定
      fragrance_ids = Array.wrap(params[:review].dig(:fragrances, :fragrance_ids)).map(&:to_i)
      @review.fragrances = Fragrance.where(id: fragrance_ids)

      redirect_to wine_path(@wine)
    else
      render :edit
    end
  end

  def show
    @review = Review.find(params[:id])
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to user_path(current_user)
  end

  private

  def review_params
    params.require(:review).permit(
      :wine_date, :wine_bar, :image, :sweetness, :bitterness, :acidity, :alcohol, :content, fragrances: [fragrance_ids: []]
    ).merge(user: current_user)
  end

  def set_wine
    @wine = Wine.find(params[:wine_id])
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/edit.html.erb
<%= render "shared/header" %>


<p>ワイン名: <%= @wine.name %></p>
<p>種類: <%= @wine.type.name %></p>
<p>生産地: <%= @wine.region.name %></p>
<p>生産者: <%= @wine.producer %></p>



<div class="container">
    <h1 class="title">ワインのレビューを投稿しよう</h1>
    <%= form_with model: [@wine, @review], url: wine_review_path(@wine, @review), local: true, html: { class: "review-form" } do |form| %>
        <div class="wine-info">
            
        </div>

        
        <div class="form-row">
            <div class="form-group">
                <%= form.label :wine_date, "日付" %>
                <%= form.date_field :wine_date, id: "wine_date", class: "form-control" %>
            </div>
            <div class="form-group">
                <%= form.label :wine_bar, "お店" %>
                <%= form.text_field :wine_bar, id: "wine_bar", placeholder: "購入店や飲食店、自宅など", class: "form-control"  %>
            </div>
        </div>
        <div class="form-group image-upload-group">
            <%= form.label :image, "写真" %>
            <div class="image-upload-container">
                <%= form.file_field :image, id: "image" %>
                <img id="preview" src="" alt="Image preview" style="display: none; width: 200px; height: 200px;">
            </div>
        </div>


        <div class="attributes-container">
            <% grouped_attributes = Review.wine_attributes.each_slice(2).to_a %>
            <% grouped_attributes.each do |attribute_pair| %>
                <div class="attribute-row">
                    <% attribute_pair.each do |attribute| %>
                        <div class="form-group">
                            <% label_text = { sweetness: "甘み", bitterness: "渋み", acidity: "酸味", alcohol: "アルコール" }[attribute] %>
                            <%= form.label attribute, label_text, class: "attribute-label" %>
                            <div class="radio-options">
                                <% WineAttribute.all.each do |option| %>
                                    <label class="radio-label">
                                        <%= form.radio_button attribute, option.id, id: "#{attribute}_#{option.id}" %>
                                        <%= option.name %>
                                    </label>
                                <% end %>
                            </div>
                        </div>
                    <% end %>
                </div>
            <% end %>
        </div>

        <div class="form-group">
            <button type="button" class="btn fragrance-select-btn" data-bs-toggle="modal" data-bs-target="#fragranceModal">
                香りを選択
            </button>
            <!-- モーダルウィンドウ -->
            <div class="modal fade" id="fragranceModal" tabindex="-1" aria-labelledby="fragranceModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="fragranceModalLabel">香りの選択</h5>
                            <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">×</button>
                        </div>
                        <div class="modal-body">
                            <% Fragrance.all.group_by(&:category).each do |category, fragrances| %>
                                <div class="fragrance-category">
                                <h4><%= category %></h4>
                                <div class="fragrance-items-container">
                                    <% fragrances.each do |fragrance| %>
                                    <div class="fragrance-item">
                                        <%= check_box_tag "review[fragrances][fragrance_ids][]", fragrance.id, @review.fragrances.include?(fragrance), id: "fragrance_#{fragrance.id}" %>
                                        <%= label_tag "fragrance_#{fragrance.id}", fragrance.name %>
                                    </div>
                                    <% end %>
                                </div>
                                </div>
                            <% end %>
                            </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">閉じる</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            <%= form.label :content, "その他感想など" %>
            <%= form.text_area :content, id: "content", placeholder: "風味や香り、お店、料理など", rows: "4", maxlength: "1000" %>
        </div>

        <div class="form-actions">
            <%= form.submit "更新する", class: "btn submit-btn" %>
        </div>
    <% end %>
</div>

<%= render "shared/footer" %>

app/views/reviews/index.html.erb
          
      <%= render "shared/header" %>

          <main>
            <div class="main-first">  
              
              <div class="background-image">
              <%= image_tag "back_ground_image.jpg", class: "background-image" %>
              </div>
  
              
              <div class="logo"><%= image_tag "wine_nomitai.png", class:"logo" %> </div>

              <!-- モーダルウィンドウ -->
              <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#searchModal">
                条件を絞って検索する
              </button>
              
              <div class="modal fade" id="searchModal" tabindex="-1" aria-labelledby="searchModalLabel" aria-hidden="true">
                <div class="modal-dialog  modal-lg">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="searchModalLabel">検索条件</h5>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                  <%= form_with url: search_wines_path, method: :get, local: true do |f| %>
                      <div class="checkbox-container">
                        <h5>ワインの種類</h5>
                        <div class="checkbox-group">
                          <% Type.all.each do |type| %>
                            <div class="checkbox-item">
                              <%= check_box_tag "type_ids[]", type.id, false, id: "type_id_#{type.id}" %>
                              <%= label_tag "type_id_#{type.id}", type.name %>
                            </div>
                          <% end %>
                        </div>
                      </div>

                      <div class="checkbox-container">
                        <h5>ワインの生産地</h5>
                        <div class="checkbox-group">
                          <% Region.all.each do |region| %>
                            <div class="checkbox-item">
                              <%= check_box_tag "region_ids[]", region.id, false, id: "region_id_#{region.id}" %>
                              <%= label_tag "region_id_#{region.id}", region.name %>
                            </div>
                          <% end %>
                        </div>
                      </div>

                      <div class="checkbox-container">
                        <h5>ブドウの品種</h5>
                        <div class="checkbox-group">
                          <% GrapeVariety.all.each do |grape_variety| %>
                            <div class="checkbox-item">
                              <%= check_box_tag "grape_variety_ids[]", grape_variety.id, false, id: "grape_variety_id_#{grape_variety.id}" %>
                              <%= label_tag "grape_variety_id_#{grape_variety.id}", grape_variety.name %>
                            </div>
                          <% end %>
                        </div>
                      </div>

                      <div class="modal-footer">
                        <%= f.submit "検索", class: "btn btn-primary" %>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>  
            <!-- モーダルウィンドウ -->

              <%= form_with url: search_wines_path, method: :get, local: true, html: {class: "search-container"} do |form| %>
              <%= text_field_tag :keyword, nil, id: 'wine_search', placeholder: "キーワード・ワイン名・生産者名", style: "width: 220px; height: 80px;" %>
              <%= submit_tag "検索", class: "search-container-button", style: "height: 80px; width: 60px;" %>
              <% end %>
              </div>

                    
        
            </div>
            <div class="new-reviews-area">
              <div class="new-reviews">新着レビュー</div>
            </div>


            <%= render "shared/review_index"%>
            
          

          </main> 

      <%= render "shared/footer" %>

      

app/views/reviews/new.html.erb
<%= render "shared/header" %>


<p>ワイン名: <%= @wine.name %></p>
<p>種類: <%= @wine.type.name %></p>
<p>生産地: <%= @wine.region.name %></p>
<p>生産者: <%= @wine.producer %></p>


<div class="container">
    <h1 class="title">ワインのレビューを投稿しよう</h1>
    
    <%= form_with model: [@wine, @review], url: wine_reviews_path, local: true, html: { class: "review-form" } do |form| %>
       
            
        

        
        <div class="form-row">
            <div class="form-group">
                <%= form.label :wine_date, "日付" %>
                <%= form.date_field :wine_date, id: "wine_date", class: "form-control" %>
            </div>
            <div class="form-group">
                <%= form.label :wine_bar, "お店" %>
                <%= form.text_field :wine_bar, id: "wine_bar", placeholder: "購入店や飲食店、自宅など", class: "form-control"  %>
            </div>
        </div>
        <div class="form-group image-upload-group">
            <%= form.label :image, "写真" %>
            <div class="image-upload-container">
                <%= form.file_field :image, id: "image" %>
                <img id="preview" src="" alt="Image preview" style="display: none; width: 200px; height: 200px;">
            </div>
        </div>


        <div class="attributes-container">
            <% grouped_attributes = Review.wine_attributes.each_slice(2).to_a %>
            <% grouped_attributes.each do |attribute_pair| %>
                <div class="attribute-row">
                    <% attribute_pair.each do |attribute| %>
                        <div class="form-group">
                            <% label_text = { sweetness: "甘み", bitterness: "渋み", acidity: "酸味", alcohol: "アルコール" }[attribute] %>
                            <%= form.label attribute, label_text, class: "attribute-label" %>
                            <div class="radio-options">
                                <% WineAttribute.all.each do |option| %>
                                    <label class="radio-label">
                                        <%= form.radio_button attribute, option.id, id: "#{attribute}_#{option.id}" %>
                                        <%= option.name %>
                                    </label>
                                <% end %>
                            </div>
                        </div>
                    <% end %>
                </div>
            <% end %>
        </div>

        <div class="form-group">
            <button type="button" class="btn fragrance-select-btn" data-bs-toggle="modal" data-bs-target="#fragranceModal">
                香りを選択
            </button>
            <!-- モーダルウィンドウ -->
            <div class="modal fade" id="fragranceModal" tabindex="-1" aria-labelledby="fragranceModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="fragranceModalLabel">香りの選択</h5>
                            <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">×</button>
                        </div>
                        <div class="modal-body">
                            <%= form.fields_for :fragrances, @review do |fragrance_fields| %>
                        <% Fragrance.all.group_by(&:category).each do |category, fragrances| %>
                            <div class="fragrance-category">
                            <h4><%= category %></h4>
                            <div class="fragrance-items-container">
                                <% fragrances.each do |fragrance| %>
                                <div class="fragrance-item">
                                    <%= fragrance_fields.check_box :fragrance_ids, { multiple: true, id: "fragrance_#{fragrance.id}" }, fragrance.id, nil %>
                                    <%= label_tag "fragrance_#{fragrance.id}", fragrance.name %>
                                </div>
                                <% end %>
                            </div>
                            </div>
                        <% end %>
                        <% end %>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">閉じる</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            <%= form.label :content, "その他感想など" %>
            <%= form.text_area :content, id: "content", placeholder: "風味や香り、お店、料理など", rows: "4", maxlength: "1000" %>
        </div>

        <div class="form-actions">
            <%= form.submit "投稿する", class: "btn submit-btn" %>
        </div>
    <% end %>
</div>

<%= render "shared/footer" %>

app/views/reviews/show.html.erb
<%= render "shared/header" %>

<div class="reviews-show">

  <div class="review-show">     
            
            <div class="review-top">
            <%= link_to(image_tag(@review.user.avatar, alt: @review.user.nickname, class: "avatar"), user_path(@review.user)) %>
            
            <div class="date-name">
            <div class="wine-date"><%= @review.wine_date %></div>
            <div class="user-name"><%= link_to @review.user.nickname, user_path(@review.user), class: "user-name-color" %></div>
            </div>
            
            <div class="wine-name">
              <%= link_to "#{@review.wine.name} （ #{Region.find(@review.wine.region_id).name} ）", wine_path(@review.wine), class: "wine-name-color" %>
            </div>
            
          </div>

            <div class="show-review-content">
              <div class="review-image">
                <% if @review.image.attached? %>
                  <%= link_to image_tag(@review.image, class: "review-image"), "#" %>
                <% end %>
              </div>
              
              <div class="review-right">
                <div class="show-review-text"><%= @review.content %></div>
                <ul class="edit-destroy">
                  <% if user_signed_in? && @review.user == current_user %>  
                    <li><%= link_to "編集", edit_wine_review_path(wine_id: @review.wine_id, id: @review.id), class: "edit-link" %></li>
                    <li><%= link_to "削除", review_path(wine_id: @review.wine_id, id: @review.id), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "delete-link" %></li>
                  <% end %>
                </ul>
                <div class="review-right-bottom">
                  
                  <div class="review-fragrance">
                      <% @review.fragrances.each do |fragrance| %>
                        <span class="review-fragrance-item">#<%= fragrance.name %></span>
                      <% end %>
                  </div>
                  
                  <div class="review-four-elements">
                      <ul>
                        <% attribute_names = { sweetness: '甘味', bitterness: '苦味', acidity: '酸味', alcohol: 'アルコール' } %>
                        <% Review.wine_attributes.each do |attribute| %>
                          <li>
                            <%= attribute_names[attribute] %>
                            <% rating = @review.send(attribute) %>
                            <% if rating.present? %> <!-- 評価がある場合 -->
                              <% (1..5).each do |i| %>
                                <% if i <= rating %>
                                  <span class="star">★</span>
                                <% else %>
                                  <span class="star">☆</span>
                                <% end %>
                              <% end %>
                            <% else %> <!-- 評価がない場合 -->
                              <% (1..5).each do %> <!-- すべての星を☆で表示 -->
                                <span class="star">☆</span>
                              <% end %>
                            <% end %>
                          </li>
                        <% end %>
                      </ul>
                    </div>
                    <div class="wine-bar">
                      <div><%= image_tag "wine_bar_icon.png", alt: "店舗アイコン", class: "wine-bar-con" %></div>
                      <%= @review.wine_bar %>
                    </div>

                </div>
                


              </div>
            </div>
  
              <div class="review-bottom">
                  
                  
                 
                </div>
              </div>
                                
  </div>
      
</div>


<%= render "shared/footer" %>