config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "reviews#index"
  resources :wines, only: [:show] do
    collection do
      get 'search'
      get 'autocomplete'
    end
    resources :reviews, only: [:new, :create, :edit, :update, :show]
  end
  resources :reviews, only: [:index, :destroy]
  resources :users, only: [:edit, :update, :show]
end

app/models/wine.rb
class Wine < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  has_many :reviews
  belongs_to :region
  belongs_to :grape_variety, optional: true
  belongs_to :type
  has_one_attached :image

  validates :name, presence: true

  validates :grape_variety_id, numericality: { other_than: 1, allow_nil: true }
  validates :type_id, numericality: { other_than: 1, allow_nil: true }
  validates :region_id, numericality: { other_than: 1, allow_nil: true }
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  def show
    @wine = Wine.find(params[:id])
    @reviews = @wine.reviews
  end

  def search
    @wines = Wine.all

    # 入力されたキーワードを処理
    if params[:keyword].present?
      # 全角スペースを半角スペースに置換し、余分なスペースを削除
      keyword_processed = params[:keyword].gsub(/[[:space:]]/, ' ').strip.gsub(/\s+/, ' ')

      # 平仮名をカタカナに変換し、全角英数字を半角に変換
      keyword_processed = Moji.hira_to_kata(keyword_processed)
      keyword_processed = Moji.zen_to_han(keyword_processed, Moji::ZEN_ALNUM) # 全角英数字を半角に
      @keywords = Moji.han_to_zen(keyword_processed, Moji::KANA)
    else
      @keywords = ''
    end

    @type_names = Type.where(id: params[:type_ids]).pluck(:name).join(', ')
    @region_names = Region.where(id: params[:region_ids]).pluck(:name).join(', ')
    @grape_variety_names = GrapeVariety.where(id: params[:grape_variety_ids]).pluck(:name).join(', ')

    # 検索条件がある場合のみwhere句を使って絞り込み
    if @keywords.present?
      @wines = @wines.joins('LEFT JOIN reviews ON reviews.wine_id = wines.id')
                     .where('wines.name LIKE :keyword OR wines.producer LIKE :keyword OR reviews.content LIKE :keyword', keyword: "%#{@keywords}%")
    end

    # その他の検索条件
    @wines = @wines.where(type_id: params[:type_ids]) if params[:type_ids].present?
    @wines = @wines.where(region_id: params[:region_ids]) if params[:region_ids].present?
    @wines = @wines.where(grape_variety_id: params[:grape_variety_ids]) if params[:grape_variety_ids].present?

    @wines = @wines.distinct

    render 'search'
  end

  def autocomplete
    term = params[:term].downcase
    wines = Wine.where('LOWER(name) LIKE :term OR LOWER(producer) LIKE :term', term: "%#{term}%").select(:name,
                                                                                                         :producer).distinct
    names = wines.map { |wine| { label: "ワイン名: #{wine.name}", value: wine.name } }
    producers = wines.map { |wine| { label: "生産者名: #{wine.producer}", value: wine.producer } }.uniq
    result = names + producers
    render json: result.uniq { |item| item[:value] }
  end
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/wines/index.html.erb
<% @wines.each do |wine| %>
  <div>
    <h3><%= wine.name %> - <%= wine.producer %></h3>
    <% wine.reviews.each do |review| %>
      <p>Review: <%= review.content %></p>
    <% end %>
  </div>
<% end %>

app/views/wines/search.html.erb
<%= render "shared/header" %>

<% if @wines.present? %>
  <div class="search-result-upper">
    <% if @keywords.present? %>
      <%= @keywords %> の
    <% end %>
    検索結果一覧
    <% if @type_names.present? || @region_names.present? || @grape_variety_names.present? %>
      (<%= [@type_names, @region_names, @grape_variety_names].reject { |name| name.blank? }.join(", ") %>)
    <% end %>
    <br>
    <%= @wines.count %>件のワインがみつかりました
  </div>
  <div class="search-result">
    <% @wines.each do |wine| %>
      <div class="search-result-index">
        <div class="wine-information">
          <h3>ワイン名：<%= wine.name %></h3>
          <h3>生産者：<%= wine.producer %></h3>
          <h3>生産地：<%= wine.region.name %></h3>
          <h3>レビュー数：<%= wine.reviews.count %>件</h3>
        </div>
        <% if wine.image.attached? %>
          <%= image_tag wine.image, class: "wine-image-index" %>
        <% else %>
          <p>No Image</p>
        <% end %>
        <%= link_to "このワインの詳細へ", wine_path(wine), class: "details-link" %>
      </div>
    <% end %>
  </div>    
<% else %>
  <p>検索結果がありません。</p>
<% end %>

<%= render "shared/footer" %>

app/views/wines/show.html.erb
<%= render "shared/header" %>

<div class="wine-show-main">
  <div class="wine-show-main-center">
    <div class="wine-info">
      <ul>
        <li><strong>ワイン名:</strong> <%= @wine.name %></li>
        <li><strong>種類:</strong> <%= @wine.type.name %></li>
        <li><strong>ブドウ品種:</strong> <%= @wine.grape_variety ? @wine.grape_variety.name : '情報なし' %></li>
        <li><strong>生産地:</strong> <%= @wine.region.name %></li>
        <li><strong>生産者:</strong> <%= @wine.producer %></li>
      </ul>
    </div>

    <div class="detail-page-review-btn">
      <%= link_to(new_wine_review_path(wine_id: @wine.id)) do %>
        <div class="detail-page-review-text">このワインのレビューを投稿する</div>
      <% end %>
    </div>
  </div>

  <div class="wine-image-container">
    <% if @wine.image.attached? %>
      <%= image_tag @wine.image, class: "wine-image" %>
    <% else %>
      <p>No Image</p>
    <% end %>
  </div>
</div>

<%= render "shared/review_index" %>

<%= render "shared/footer" %>